### ISSUE TITLE
Issue with the "opensearch" plugin

### ISSUE THREAD

**Issue by hasinireddy24** [fluent/fluent-plugin-opensearch#46]
**Issue**

Hi,

I'm using the "opensearch" plugin in my fluentd configuration. And I'm deploying the fluentd in EKS. In my fluentd configuration I'm not specifying any credentials. According to the fluentd docs. It should use the EC2 Node role automatically, since no key and secret were specified in the config file. The instance's role is properly configured so OpenSearch allows access to it.

After the fluentd is deployed to EKS it is working for sometime and able to see the EKS application logs in Opensearch dashboard. But suddenly it fails to push the logs and throws the error "403 The security token included in the request is expired"

**Issue log**

```
2022-04-02 08:47:08 +0000 [debug]: #0 taking back chunk for errors. chunk="5dba7ec9f97cdf62e400104e550793cc"
2022-04-02 08:47:08 +0000 [warn]: #0 failed to flush the buffer. retry_times=4 next_retry_time=2022-04-02 08:47:15 +0000 chunk="5dba7ec9f97cdf62e400104e550793cc" error_class=Fluent::Plugin::OpenSearchOutput::RecoverableRequestFailure error="could not push logs to OpenSearch cluster ({:host=>\"vpcxxxxxxxxx\", :port=>443, :scheme=>\"https\"}): [403] {\"message\":\"**The security token included in the request is expired**/"
```
#### Expected Behavior or What you need to ask
The issue is occurring randomly like after 20hrs, 10hrs and sometimes after 2days. To resolve this issue we need to refresh the fluentd pods.

But the strange thing is it is automatically starts working after 2,3 hrs. Firstly, I thought it might be the issue with the Role which I'm using to connect with opensearch. But after doing troubleshooting now I can clearly understands that there is a issue with the plugin itself.

**Steps to replicate**
DockeFile file used for deploying fluentd to Kubernetes

```
FROM fluent/fluentd-kubernetes-daemonset:v1.14-debian-kafka-1
USER root
RUN gem install fluent-plugin-opensearch
RUN gem install fluent-plugin-concat
RUN gem install fluent-plugin-stdout-pp
RUN gem install fluent-plugin-multi-format-parser
```
```
<match kubernetes>
        @type opensearch
        ssl_verify false
        @log_level debug
        logstash_format true
        logstash_prefix jb-app-log-java # defaults to "logstash"
        logstash_prefix_separator -     # defaults to "-"
        logstash_dateformat %Y.%m       # defaults to "%Y.%m.%d"     
        <endpoint>
          url    https://vpc.xxxx.com
          region us-xxx-1
        </endpoint>
        <buffer>
          @type memory
        </buffer>
      </match>


```
#### Using Fluentd and OpenSearch plugin versions

Using the fluent-opensearch-plugin lastest version

Please have a look into the issue. Any help is appreciated.
Thanks in advance!!

**Comment by cosmo0920** [comment]
Duplicated with https://github.com/fluent/fluent-plugin-opensearch/issues/24?

**Comment by kyleli666** [comment]
I have the same issue here with bare metal td-agent on an AWS Ubuntu EC2.

1. I have the IAM role with AWS opensearch access attached to my EC2, and it works fine with the old fluent-plugin-aws-elasticsearch-service.
2. With the `curl http://169.254.169.254/latest/meta-data/iam/security-credentials/examplerole`, I can see the token expires after about 6 hours, and it renews every several minutes.
3. But, the opensearch plugin seems only uses the first token it got when td-agent start (or restart), and never re-get the new token in the later requests. Just after about 6 hours, I get the error {\"message\":\"The security token included in the request is expired\"}.

I was observing the process of this issue all the day today, I feel it's a bug now.

I have to turn back to the old aws-elasticsearch plugin, and block my td-agent version at 4.2.0, because there is some other compatibility issue.

**Comment by kyleli666** [comment]
I think I found a workaround for this issue, which works for me.
Add these lines in "match" configuration:
```
reload_connections false
reconnect_on_error true
reload_on_failure true
```
Although, the "token expire" warning still appears from time to time,  but as the reconnect works, the application will keep running.

**Comment by cosmo0920** [comment]
Hi, how about trying to patch #52? Does it effective for this issue?

**Comment by cosmo0920** [comment]
Hi, how about trying to patch #52? Does it effective for this issue?
